# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resources\rgb_to_hsl.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QPushButton, QLineEdit, QLabel


class Ui_Dialog_RGB_to_HSL(object):
    def setupUi(self, Dialog_RGB_to_HSL):
        Dialog_RGB_to_HSL.setObjectName("Dialog_RGB_to_HSL")
        Dialog_RGB_to_HSL.resize(202, 128)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_RGB_to_HSL)
        self.buttonBox.setGeometry(QtCore.QRect(-160, 90, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QPushButton(Dialog_RGB_to_HSL)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QtCore.QRect(60, 90, 75, 23))
        self.label = QtWidgets.QLabel(Dialog_RGB_to_HSL)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_RGB_to_HSL)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 47, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_RGB_to_HSL)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 47, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog_RGB_to_HSL)
        self.lineEdit.setGeometry(QtCore.QRect(40, 20, 31, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog_RGB_to_HSL)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 40, 31, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog_RGB_to_HSL)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 60, 31, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(Dialog_RGB_to_HSL)
        self.label_4.setGeometry(QtCore.QRect(130, 40, 47, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog_RGB_to_HSL)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 40, 31, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(Dialog_RGB_to_HSL)
        self.label_5.setGeometry(QtCore.QRect(130, 60, 47, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog_RGB_to_HSL)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 20, 31, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(Dialog_RGB_to_HSL)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(130, 20, 47, 20))
        self.label_6.setObjectName("label_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog_RGB_to_HSL)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 60, 31, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.retranslateUi(Dialog_RGB_to_HSL)

        QtCore.QMetaObject.connectSlotsByName(Dialog_RGB_to_HSL)

    def retranslateUi(self, Dialog_RGB_to_HSL):
        _translate = QtCore.QCoreApplication.translate
        Dialog_RGB_to_HSL.setWindowTitle(_translate("Dialog_RGB_to_HSL", "Dialog"))
        self.label.setText(_translate("Dialog_RGB_to_HSL", "R:"))
        self.label_2.setText(_translate("Dialog_RGB_to_HSL", "G:"))
        self.label_3.setText(_translate("Dialog_RGB_to_HSL", "B:"))
        self.label_4.setText(_translate("Dialog_RGB_to_HSL", "S:"))
        self.label_5.setText(_translate("Dialog_RGB_to_HSL", "V:"))
        self.label_6.setText(_translate("Dialog_RGB_to_HSL", "H:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_RGB_to_HSL = QtWidgets.QDialog()
    ui = Ui_Dialog_RGB_to_HSL()
    ui.setupUi(Dialog_RGB_to_HSL)
    Dialog_RGB_to_HSL.show()
    sys.exit(app.exec_())
