# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resources\widgetDesenho.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        # Form.setObjectName("Form")
        # Form.resize(400, 300)
        # self.label = QtWidgets.QLabel(Form)
        # # self.label.setGeometry(QtCore.QRect(10, 10, 371, 271))
        # canvas = QtGui.QPixmap(380, 280)
        # canvas.fill(QtCore.Qt.white)
        # self.label.setPixmap(canvas)
        # self.label.setObjectName("label")
        # # self.desenhar(self.label.mousePressEvent., canvas)

        self.label = QtWidgets.QLabel()
        canvas = QtGui.QPixmap(400, 300)
        self.label.setGeometry(QtCore.QRect(20, 70, 700, 555))
        self.label.setPixmap(canvas)
        # self.label.setLayout(QtWidgets.QVBoxLayout())
        self.draw_something()

    def draw_something(self):
        print("ayyy")
        painter = QtGui.QPainter(self.label.pixmap())
        painter.drawLine(10, 10, 300, 200)
        painter.end()


        # self.label.mousePressEvent = self.desenhar

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    # draws a red pixel on the exact spot left clicked by user mouse, and updates the label
    def desenhar(self, event):
        x = event.x()
        y = event.y()
        # self.label.setPixmap(QtGui.QPixmap.fromImage(self.image))
        canvas.setPixel(x, y, QtGui.QColor(255, 0, 0).rgb())
        self.label.setPixmap(QtGui.QPixmap.fromImage(self.canvas))


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
