# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resources\widgetRGB.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(877, 300)
        self.foto = QtWidgets.QLabel(Form)
        self.foto.setGeometry(QtCore.QRect(20, 70, 241, 131))
        self.foto.setObjectName("foto")
        self.foto_2 = QtWidgets.QLabel(Form)
        self.foto_2.setGeometry(QtCore.QRect(290, 80, 241, 131))
        self.foto_2.setObjectName("foto_2")
        self.foto_3 = QtWidgets.QLabel(Form)
        self.foto_3.setGeometry(QtCore.QRect(590, 80, 241, 131))
        self.foto_3.setObjectName("foto_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.foto.setText(_translate("Form", "TextLabel"))
        self.foto_2.setText(_translate("Form", "TextLabel"))
        self.foto_3.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
